sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t taubar/algohike-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true taubar/algohike-test npm test

after_success:
  - docker build -t taubar/algohike-frontend ./frontend
  - docker build -t taubar/algohike-nginx ./nginx
  - docker build -t taubar/algohike-matching-service ./matching-service
  - docker build -t taubar/algohike-collab-service ./collab-service
  - docker build -t taubar/algohike-communication-service ./communication-service
  - docker build -t taubar/algohike-question-service ./question-service
  - docker build -t taubar/algohike-user-service ./user-service