version: "3"

services:
  question-service:
    build:
      context: ./question-service
    command: npm start
    ports:
      - "8081:8081"
    
  matching-service:
    build:
      context: ./matching-service
    command: npm start
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq

  mongo:
    container_name: "mongo-node"
    platform: linux/amd64
    image: mongo:4.4.14
    ports:
      - "8082:8082"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq