apiVersion: apps/v1
kind: Deployment
metadata:
  name: collab-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collab
  template:
    metadata:
      labels:
        app: collab
    spec:
      containers:
        - name: collab
          image: taubar/algohike-collab-service
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ENV
              value: production
            - name: PORT
              value: '8080'
            - name: URI_QUESTION_SERVICE
              value: http://question-cluster-ip-service:8081
            - name: DB_LOCAL_URI
              value: mongodb://mongo-cluster-ip-service:27017/collab