apiVersion: v1
kind: Service
metadata:
  name: communication-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: communication
  ports:
    - name: http
      port: 9000
      targetPort: 9000